"""empty message

Revision ID: 04cfb38e0d24
Revises: b692de7873f7
Create Date: 2020-02-20 00:03:10.059043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cfb38e0d24'
down_revision = 'b692de7873f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pontos', sa.Column('id_aluno', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pontos', 'alunos', ['id_aluno'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pontos', type_='foreignkey')
    op.drop_column('pontos', 'id_aluno')
    # ### end Alembic commands ###
