"""empty message

Revision ID: 174a2a641737
Revises: c6d706416798
Create Date: 2020-02-20 00:27:58.328527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174a2a641737'
down_revision = 'c6d706416798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pontos', 'alunos', ['id_aluno'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pontos', type_='foreignkey')
    # ### end Alembic commands ###
