"""empty message

Revision ID: 1b8c0dadcce3
Revises: 9e5c1211a128
Create Date: 2020-02-20 00:48:27.487337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8c0dadcce3'
down_revision = '9e5c1211a128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pontos', 'id_aluno',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pontos', 'id_aluno',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
