"""empty message

Revision ID: 42cf7cd59475
Revises: 1b8c0dadcce3
Create Date: 2020-02-20 01:12:50.768513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cf7cd59475'
down_revision = '1b8c0dadcce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('id_ponto', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'alunos', 'pontos', ['id_ponto'], ['id'])
    op.drop_constraint(None, 'pontos', type_='foreignkey')
    op.drop_column('pontos', 'id_aluno')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pontos', sa.Column('id_aluno', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'pontos', 'alunos', ['id_aluno'], ['id'])
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.drop_column('alunos', 'id_ponto')
    # ### end Alembic commands ###
