"""empty message

Revision ID: 4f7200b17595
Revises: 750248e8ab4f
Create Date: 2020-02-23 01:41:25.945342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7200b17595'
down_revision = '750248e8ab4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chegada', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('chegada', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chegada', 'lon')
    op.drop_column('chegada', 'lat')
    # ### end Alembic commands ###
