"""empty message

Revision ID: 524cd3c21074
Revises: 42cf7cd59475
Create Date: 2020-02-20 01:15:05.379241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524cd3c21074'
down_revision = '42cf7cd59475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('escola', sa.String(length=100), nullable=False),
    sa.Column('turno', sa.String(length=100), nullable=False),
    sa.Column('presenca', sa.Integer(), nullable=False),
    sa.Column('id_ponto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ponto'], ['pontos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos')
    op.drop_table('pontos')
    # ### end Alembic commands ###
