"""empty message

Revision ID: 564a8b1b1317
Revises: 174a2a641737
Create Date: 2020-02-20 00:31:57.272633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564a8b1b1317'
down_revision = '174a2a641737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pontos', 'alunos', ['id_aluno'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pontos', type_='foreignkey')
    # ### end Alembic commands ###
