"""empty message

Revision ID: 6753284f1a00
Revises: aef6cea67e17
Create Date: 2020-02-23 01:36:07.253712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6753284f1a00'
down_revision = 'aef6cea67e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chegada', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('chegada', sa.Column('lon', sa.Float(), nullable=False))
    op.add_column('pontos', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('pontos', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pontos', 'lon')
    op.drop_column('pontos', 'lat')
    op.drop_column('chegada', 'lon')
    op.drop_column('chegada', 'lat')
    # ### end Alembic commands ###
