"""empty message

Revision ID: 750248e8ab4f
Revises: 6753284f1a00
Create Date: 2020-02-23 01:40:15.420927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750248e8ab4f'
down_revision = '6753284f1a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chegada', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('chegada', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('pontos', 'lon')
    op.drop_column('pontos', 'lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pontos', sa.Column('lat', sa.REAL(), nullable=True))
    op.add_column('pontos', sa.Column('lon', sa.REAL(), nullable=True))
    op.drop_column('chegada', 'lon')
    op.drop_column('chegada', 'lat')
    # ### end Alembic commands ###
