"""empty message

Revision ID: 9d16df7831ae
Revises: 0870443f2bef
Create Date: 2020-02-20 00:35:20.785570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d16df7831ae'
down_revision = '0870443f2bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pontos', 'alunos', ['id_aluno'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pontos', type_='foreignkey')
    # ### end Alembic commands ###
