"""empty message

Revision ID: 9e5c1211a128
Revises: 9d16df7831ae
Create Date: 2020-02-20 00:36:03.703831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5c1211a128'
down_revision = '9d16df7831ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('escola', sa.String(length=100), nullable=False),
    sa.Column('turno', sa.String(length=100), nullable=False),
    sa.Column('presenca', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pontos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
