"""empty message

Revision ID: c6d706416798
Revises: 86a55c433700
Create Date: 2020-02-20 00:25:39.485112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d706416798'
down_revision = '86a55c433700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pontos', sa.Column('id_aluno', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pontos', 'alunos', ['id_aluno'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pontos', type_='foreignkey')
    op.drop_column('pontos', 'id_aluno')
    # ### end Alembic commands ###
